name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Obtener el código del repositorio
      uses: actions/checkout@v4

    - name: Preparar el entorno con Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Instalar dependencias
      run: npm install
      
    - name: Ejecutar pruebas (Test)
      run: npm test
